// apps/web-react/src/index.tsx
/**
 * @file 应用入口
 */
import React, { useState } from "react";
import ReactDOM from "react-dom/client";

import { history, app } from "~/store/index";
import { PageKeys } from "~/store/routes";
import { pages } from "~/store/views";
import { client } from "~/store/http_client";
import { ThemeProvider } from "~/components/theme-switch";
import { StackRouteView } from "~/components/ui/stack-route-view";
import { Toast, Dialog } from "~/components/ui";

import { ToastCore } from "@/domains/ui/toast";
import { DialogCore } from "@/domains/ui/index";
import { cn } from "@/utils/index";

import { useViewModel, useInitialize, useInstance } from "./hooks";

import "./index.css";

const view = history.$view;

function ApplicationView() {
  const $toast = useInstance(() => new ToastCore());
  const $upgrade = useInstance(
    () =>
      new DialogCore({
        title: "升级提示",
        // cancel: false,
        onOk() {
          window.location.reload();
        },
      })
  );
  // const [showMask, setShowMask] = useState(true);
  // const [ready, setReady] = useState(false);
  const [error, setError] = useState<Error | null>(null);
  const [subViews, setSubViews] = useState(view.subViews);

  useInitialize(() => {
    view.onSubViewsChange((v) => {
      // console.log("[ROOT]rootView.onSubViewsChange", nextSubViews.length);
      setSubViews(v);
    });
    app.onTip((msg) => {
      const { text } = msg;
      $toast.show({
        texts: text,
      });
    });
    app.onUpdate(() => {
      $upgrade.show();
    });
    app.onError((err) => {
      setError(err);
    });
    const { innerWidth, innerHeight, location } = window;
    history.$router.prepare(location);
    app.start({
      width: app.env.pc ? 375 : innerWidth,
      height: innerHeight,
    });
  });

  // console.log("[ROOT]renderer - render", subViews);

  if (error) {
    return (
      <div
        className={cn("fixed inset-0 z-10")}
        onClick={() => {
          history.reload();
        }}
      >
        <div className="w-screen h-screen flex items-center justify-center">
          <div>
            <div className="text-3xl text-center">{error.message}</div>
            <div className="mt-4 text-center">
              请根据上述提示进行操作，或者点击刷新
            </div>
          </div>
        </div>
      </div>
    );
  }

  return (
    <>
      {/* {showMask && (
        <div
          className={cn(
            "app__mask fixed inset-0 z-10 bg-yellow-300",
            ready ? "opacity-0 scale-150" : "opacity-100 scale-100"
          )}
        >
          <div className="w-screen h-screen flex items-center justify-center">
            <div>
              <div>Test Page</div>
              <div>Welcome using the video site</div>
            </div>
          </div>
        </div>
      )} */}
      <div className={cn("screen w-screen h-screen")}>
        {subViews.map((subView, index) => {
          const routeName = subView.name;
          const PageContent = pages[routeName as Exclude<PageKeys, "root">];
          return (
            <StackRouteView
              key={index}
              className={cn(
                "z-10 fixed left-1/2 top-0 h-full mx-auto bg-w-bg-3 shadow-xl opacity-100 -translate-x-1/2",
                app.env.pc ? "w-[375px]" : "w-full"
              )}
              store={subView}
              index={10 + index}
            >
              <PageContent
                app={app}
                history={history}
                client={client}
                storage={app.$storage}
                pages={pages}
                view={subView}
              />
            </StackRouteView>
          );
        })}
        {/* <Show when={app.env.pc}>
          <div className={cn("z-0 fixed left-1/2 top-0 -translate-x-1/2", app.env.pc ? "w-[375px]" : "w-full")}>
            <div className="right-0 p-4" style={{ transform: `translateX(100%)` }}>
              <div className="rounded-md bg-w-bg-3">
                <div className="w-[60px] h-[60px]"></div>
              </div>
            </div>
          </div>
        </Show> */}
      </div>
      <Toast store={$toast} />
      <Dialog store={$upgrade}>
        <div>当前版本过旧，点击确定升级</div>
      </Dialog>
      {/* <HistoryPanel store={history} /> */}
      {/* <MediaQueryTip /> */}
    </>
  );
}

ReactDOM.createRoot(document.getElementById("root") as HTMLElement).render(
  <React.StrictMode>
    <ThemeProvider>
      <ApplicationView />
    </ThemeProvider>
  </React.StrictMode>
);

// apps/web-solid/src/index.tsx
/* @refresh reload */

import { createSignal, For, onMount, Show } from "solid-js";
import { render } from "solid-js/web";
import { LoaderCircle } from "lucide-solid";

import { app, history } from "./store/index";
import { storage } from "./store/storage";
import { client } from "./store/http_client";
import { PageKeys } from "./store/routes";
import { pages } from "./store/views";
import { KeepAliveRouteView } from "./components/ui";
import { Toast } from "./components/ui/toast";
import { RouteChildren } from "./components/route-children";

import { ToastCore } from "@timeless/domains";
import { RequestCore } from "@timeless/domains";

import "./style.css";

function Application() {
  const view = history.$view;
  const toast = new ToastCore();

  const [state, setState] = createSignal(app.state);
  const [views, setViews] = createSignal(view.subViews);

  app.onStateChange((v) => setState(v));
  view.onSubViewsChange((v) => setViews(v));

  app.onTip((msg) => {
    const { icon, text } = msg;
    toast.show({
      icon,
      texts: text,
    });
    // request.show_error.run({
    //   title: "发生错误",
    //   content: text.join("\n"),
    // });
  });
  app.onLoading((msg) => {
    const { text } = msg;
    toast.show({
      icon: "loading",
      texts: text,
    });
  });
  app.onHideLoading(() => {
    toast.hide();
  });
  onMount(() => {
    const { innerWidth, innerHeight, location } = window;
    history.$router.prepare(location);
    app.start({
      width: innerWidth,
      height: innerHeight,
    });
  });

  return (
    <div
      class="screen w-screen h-screen transition-all duration-120"
      style={{ transform: `translateY(${-state().height}px)` }}
    >
      <Show when={!state().ready}>
        <div class="flex items-center justify-center w-full h-full">
          <div class="flex flex-col items-center text-w-fg-1">
            <LoaderCircle class="w-8 h-8 animate-spin" />
            <div class="mt-4 text-center">正在加载</div>
          </div>
        </div>
      </Show>
      <RouteChildren
        app={app}
        client={client}
        storage={storage}
        pages={pages}
        history={history}
        view={view}
      />
      {/* <Show when={views().length !== 0}>
        <For each={views()}>
          {(subView, i) => {
            const routeName = subView.name;
            const PageContent = pages[routeName as Exclude<PageKeys, "root">];
            return (
              <KeepAliveRouteView class="h-full" app={app} store={subView} index={i()} classList={{}}>
                <PageContent
                  app={app}
                  history={history}
                  storage={storage}
                  pages={pages}
                  client={client}
                  view={subView}
                />
              </KeepAliveRouteView>
            );
          }}
        </For>
      </Show> */}
      <Toast store={toast} />
    </div>
  );
}
const root = document.getElementById("root");

if (import.meta.env.DEV && !(root instanceof HTMLElement)) {
  throw new Error(
    "Root element not found. Did you forget to add it to your index.html? Or maybe the id attribute got mispelled?"
  );
}
render(() => <Application />, root!);
