// platform/react/components/ui/affix.tsx
import React, { useEffect, useState } from "react";

import { useInitialize } from "~/hooks/index";
import { AffixCore } from "@/domains/ui/affix";
import { cn } from "@/utils/index";

export const Affix = React.memo(
  (props: { store: AffixCore } & React.HTMLAttributes<HTMLDivElement>) => {
    const { store, ...restProps } = props;
    const [state, setState] = useState(store.state);

    useInitialize(() => {
      store.onStateChange((v) => {
        setState(v);
      });
    });
    //   const background = (() => {
    //     if (!backgroundMap) {
    //       return "initial";
    //     }
    //     if (state.fixed) {
    //       return backgroundMap.fixed;
    //     }
    //     return backgroundMap.unfixed;
    //   })();
    const styles: React.CSSProperties = {
      ...restProps.style,
      //     ...state.style,
      position: state.fixed ? "fixed" : "unset",
      top: state.top,
    };
    //   if (background) {
    //     styles.background = background;
    //   }

    return (
      <div className="affix">
        <div
          className={cn("__a", restProps.className)}
          style={styles}
          onAnimationEnd={(event) => {
            const $node = event.currentTarget;
            //   store.setNode($node);
            store.setRect(() => {
              const rect = $node.getBoundingClientRect();
              return {
                top: rect.top,
                height: rect.height,
              };
            });
            const rect = $node.getBoundingClientRect();
            store.handleMounted(rect);
            //   if (!store.needRegisterAgain) {
            //     return;
            //   }
            //   store.register({
            //     top: rect.top,
            //     height: rect.height,
            //   });
          }}
        >
          {props.children}
        </div>
        {state.fixed && <div style={{ height: state.height }} />}
      </div>
    );
  }
);

// packages/solidjs/src/affix.tsx
import { Show } from "solid-js";
import { JSX } from "solid-js/jsx-runtime";

import { useViewModelStore } from "@/hooks";

import { ui } from "@timeless/domains";
const { AffixCore } = ui

export function Affix(props: { store: typeof AffixCore } & JSX.HTMLAttributes<HTMLDivElement>) {
  const [state, vm] = useViewModelStore(props.store);
  const styles = () => {
    return {
      position: state().fixed ? "fixed" : ("unset" as any),
      top: `${state().top}px`,
    };
  };

  return (
    <div class="affix">
      <div
        class="__a"
        classList={{
          [props.class ?? ""]: true,
        }}
        style={styles()}
        onAnimationEnd={(event) => {
          const $node = event.currentTarget;
          vm.setRect(() => {
            const rect = $node.getBoundingClientRect();
            return {
              top: rect.top,
              height: rect.height,
            };
          });
          const rect = $node.getBoundingClientRect();
          vm.handleMounted(rect);
        }}
      >
        {props.children}
      </div>
      <Show when={state().fixed}>
        <div style={{ height: `${state().height}px` }} />
      </Show>
    </div>
  );
}
