// apps/web-solid/src/packages/ui/dialog.tsx
/**
 * @file 弹窗 组件
 */
import { createSignal, JSX } from "solid-js";

import { DialogCore } from "@/domains/ui/dialog";
import { Presence } from "~/components/ui/presence";
import { Button } from "~/components/ui/button";
import { cn } from "@/utils";

import { Portal as PortalPrimitive } from "./portal";

const Root = (props: { store: DialogCore } & JSX.HTMLAttributes<HTMLElement>) => {
  return props.children;
};

const Portal = (
  props: { store: DialogCore; enterClassName?: string; exitClassName?: string } & JSX.HTMLAttributes<HTMLElement>
) => {
  return (
    <Presence store={props.store.present} classList={props.classList}>
      <PortalPrimitive>{props.children}</PortalPrimitive>
    </Presence>
  );
};

const Overlay = (
  props: { store: DialogCore; enterClassName?: string; exitClassName?: string } & JSX.HTMLAttributes<HTMLDivElement>
) => {
  return (
    <Presence
      store={props.store.presence}
      class={cn(props.class)}
      classList={props.classList}
      onClick={() => {
        if (!props.store.closeable) {
          return;
        }
        props.store.hide();
      }}
    ></Presence>
  );
};

const Content = (
  props: { store: DialogCore; enterClassName?: string; exitClassName?: string } & JSX.HTMLAttributes<HTMLElement>
) => {
  return (
    <Presence store={props.store.presence} class={cn(props.class)} classList={props.classList}>
      {props.children}
    </Presence>
  );
};

const Close = (props: { store: DialogCore } & JSX.HTMLAttributes<HTMLElement>) => {
  const { store } = props;
  const [state, setState] = createSignal(store.state);

  store.onStateChange((nextState) => {
    setState(nextState);
  });

  return (
    <div
      class={props.class}
      classList={props.classList}
      data-state={getState(state().open)}
      onClick={() => {
        props.store.hide();
      }}
    >
      {props.children}
      <span class="sr-only">Close</span>
    </div>
  );
};

const Header = (props: {} & JSX.HTMLAttributes<HTMLElement>) => {
  return <div class={cn(props.class)}>{props.children}</div>;
};

const Footer = (props: {} & JSX.HTMLAttributes<HTMLDivElement>) => {
  return <div class={cn(props.class)}>{props.children}</div>;
};

const Title = (props: {} & JSX.HTMLAttributes<HTMLElement>) => {
  return <div class={cn(props.class)}>{props.children}</div>;
};

const Submit = (props: { store: DialogCore } & JSX.HTMLAttributes<HTMLButtonElement>) => {
  const { store } = props;

  return <Button store={store.okBtn}>{props.children}</Button>;
};

const Cancel = (props: { store: DialogCore } & JSX.HTMLAttributes<HTMLButtonElement>) => {
  const { store } = props;

  return (
    <Button variant="subtle" store={store.cancelBtn}>
      {props.children}
    </Button>
  );
};

function getState(open: boolean) {
  return open ? "open" : "closed";
}

export { Root, Portal, Header, Title, Content, Close, Overlay, Footer, Submit, Cancel };

// platform/react/packages/ui/dialog.tsx
/**
 * @file 弹窗 组件
 */
import React, { useState } from "react";

import { DialogCore } from "@/domains/ui/dialog";
import { Presence } from "@/components/ui/presence";
import { Button } from "@/components/ui/button";
import { useInitialize } from "@/hooks";
import { cn } from "@/utils";

import { Portal as PortalPrimitive } from "./portal";
import { Show } from "./show";

const Root = React.memo((props: { store: DialogCore } & React.AllHTMLAttributes<HTMLElement>) => {
  return <>{props.children}</>;
});

const Portal = React.memo((props: { store: DialogCore } & React.AllHTMLAttributes<HTMLElement>) => {
  const { store } = props;

  return (
    <Presence store={store.$presence}>
      <PortalPrimitive>
        <div className={props.className}>{props.children}</div>
      </PortalPrimitive>
    </Presence>
  );
});

const Overlay = React.memo((props: { store: DialogCore } & React.AllHTMLAttributes<HTMLDivElement>) => {
  const { store } = props;

  const [state, setState] = useState(store.state);

  useInitialize(() => {
    store.onStateChange((nextState) => {
      setState(nextState);
    });
  });

  return (
    <div
      data-state={getState(state.open)}
      className={cn(props.className)}
      onClick={() => {
        store.hide();
      }}
    />
  );
});

const Content = React.memo(
  (
    props: {
      store: DialogCore;
    } & React.AllHTMLAttributes<HTMLElement>
  ) => {
    const { store } = props;
    const [state, setState] = useState(store.state);

    useInitialize(() => {
      store.onStateChange((nextState) => {
        setState(nextState);
      });
    });

    return (
      <div className={cn(props.className)} data-state={getState(state.open)}>
        {props.children}
      </div>
    );
  }
);

const Description = React.memo((props: {} & React.AllHTMLAttributes<HTMLElement>) => {
  return <div className={props.className} {...props} />;
});

const Close = React.memo((props: { store: DialogCore } & React.AllHTMLAttributes<HTMLElement>) => {
  const { store } = props;
  const [state, setState] = useState(store.state);

  useInitialize(() => {
    store.onStateChange((nextState) => {
      setState(nextState);
    });
  });

  return (
    <div
      className={props.className}
      data-state={getState(state.open)}
      onClick={() => {
        props.store.hide();
      }}
    >
      {props.children}
      <span className="sr-only">Close</span>
    </div>
  );
});

const Header = React.memo((props: {} & React.AllHTMLAttributes<HTMLElement>) => {
  return <div className={cn(props.className)}>{props.children}</div>;
});

const Footer = React.memo((props: {} & React.AllHTMLAttributes<HTMLDivElement>) => {
  return <div className={cn(props.className)}>{props.children}</div>;
});

const Title = React.memo((props: {} & React.AllHTMLAttributes<HTMLElement>) => {
  return <div className={cn(props.className)}>{props.children}</div>;
});

const Submit = React.memo((props: { store: DialogCore } & React.AllHTMLAttributes<HTMLButtonElement>) => {
  const { store } = props;

  return (
    <Button variant="default" store={store.okBtn}>
      {props.children}
    </Button>
  );
});

const Cancel = React.memo((props: { store: DialogCore } & React.AllHTMLAttributes<HTMLButtonElement>) => {
  const { store } = props;

  return (
    <Button variant="subtle" className={props.className} store={store.cancelBtn}>
      {props.children}
    </Button>
  );
});

function getState(open: boolean) {
  return open ? "open" : "closed";
}

export { Root, Portal, Header, Title, Content, Description, Close, Overlay, Footer, Submit, Cancel };
