// platform/solidjs/packages/ui/toast.tsx
/**
 * @file 小黑块 提示
 */
import { createSignal, JSX } from "solid-js";

import { Portal as PortalPrimitive } from "@/packages/ui/portal";
import { Presence } from "@/components/ui/presence";
import { ToastCore } from "@/domains/ui/toast";
import { cn } from "@/utils/index";

const Root = (props: { store: ToastCore } & JSX.HTMLAttributes<HTMLElement>) => {
  return props.children;
};

const Portal = (props: { store: ToastCore } & JSX.HTMLAttributes<HTMLDivElement>) => {
  const { store } = props;

  return (
    <Presence store={store.present}>
      <PortalPrimitive>{props.children}</PortalPrimitive>
    </Presence>
  );
};

const Overlay = (props: { store: ToastCore } & JSX.HTMLAttributes<HTMLDivElement>) => {
  const { store } = props;

  return <Presence store={store.present} class={cn(props.class)} classList={props.classList}></Presence>;
};

const Content = (props: { store: ToastCore } & JSX.HTMLAttributes<HTMLDivElement>) => {
  return (
    <div class="" classList={props.classList}>
      <Presence store={props.store.present} class={cn(props.class)}>
        {props.children}
      </Presence>
    </div>
  );
};

export { Root, Portal, Overlay, Content };

// platform/react/packages/ui/toast.tsx
/**
 * @file 小黑块 提示
 */
import React, { useState } from "react";

import { Portal as PortalPrimitive } from "@/packages/ui/portal";
import { Presence } from "@/components/ui/presence";
import { ToastCore } from "@/domains/ui/toast";
import { cn } from "@/utils";

const Root = (props: { store: ToastCore } & React.AllHTMLAttributes<HTMLElement>) => {
  return <>{props.children}</>;
};

const Portal = (props: { store: ToastCore } & React.AllHTMLAttributes<HTMLDivElement>) => {
  const { store } = props;

  return (
    <PortalPrimitive>
      <Presence store={store.$presence}>{props.children}</Presence>
    </PortalPrimitive>
  );
};

const Overlay = (props: { store: ToastCore } & React.AllHTMLAttributes<HTMLDivElement>) => {
  const { store } = props;

  const [open, setOpen] = useState(store.open);

  store.onOpenChange((nextOpen) => {
    setOpen(nextOpen);
  });

  return <div data-state={open ? "open" : "closed"} className={cn(props.className)} />;
};

const Content = (props: { store: ToastCore } & React.AllHTMLAttributes<HTMLDivElement>) => {
  const { store } = props;

  // const [open, setOpen] = useState(store.open);
  // const [state, setState] = useState(store.$present.state);

  // useInitialize(() => {
  //   store.$present.onStateChange((v) => setState(v));
  // });

  return (
    <div className="fixed z-[99] left-[50%] translate-x-[-50%] top-60 w-120 h-120 ">
      <div className={cn(props.className)}>{props.children}</div>
    </div>
  );
};

export { Root, Portal, Overlay, Content };
