// packages/solidjs/src/checkbox-group.tsx
/**
 * @file 多选按钮组件
 */
import { For, JSX, createSignal } from "solid-js";

import { ui } from "@timeless/domains";

const { CheckboxCore, CheckboxGroupCore } = ui;

export const CheckboxOption = (props: { label: string; store: CheckboxCore } & JSX.HTMLAttributes<HTMLDivElement>) => {
  const { label, store } = props;

  const [state, setState] = createSignal(store.state);

  store.onStateChange((nextState) => {
    // console.log("[COMPONENT]CheckboxGroup - Option store.onStateChange", nextState);
    setState(nextState);
  });

  return (
    <div
      classList={{
        "py-2 px-4 rounded-lg border cursor-pointer": true,
        "bg-slate-500 text-slate-200 dark:text-slate-600": !!state().checked,
        "bg-slate-500": state().checked,
      }}
      onClick={() => {
        store.toggle();
      }}
    >
      <div class="text-sm">{label}</div>
    </div>
  );
};

export const CheckboxGroup = <T extends any>(
  props: { store: CheckboxGroupCore<T> } & JSX.HTMLAttributes<HTMLDivElement>
) => {
  const { store } = props;

  const [state, setState] = createSignal(store.state);

  store.onStateChange((nextState) => {
    setState(nextState);
  });

  return (
    <div class="flex items-center flex-wrap gap-2 max-w-full">
      <For each={state().options}>
        {(opt) => {
          const { label, core } = opt;
          return <CheckboxOption store={core} label={label} />;
        }}
      </For>
    </div>
  );
};

// apps/web-react/src/components/ui/checkbox-group.tsx
import React, { useState } from "react";

import { useInitialize } from "~/hooks";
import { CheckboxCore } from "@/domains/ui/checkbox";
import { CheckboxGroupCore } from "@/domains/ui/checkbox/group";
import { cn } from "@/utils";

export const CheckboxOption = React.memo(
  (
    props: {
      label: string;
      store: CheckboxCore;
    } & React.HTMLAttributes<HTMLDivElement>
  ) => {
    const { label, store } = props;

    const [state, setState] = useState(store.state);

    useInitialize(() => {
      store.onStateChange((nextState) => {
        console.log(
          "[COMPONENT]CheckboxGroup - Option store.onStateChange",
          nextState
        );
        setState(nextState);
      });
    });

    return (
      <div
        className={cn(
          "flex justify-center items-center py-1 px-2 mb-2 rounded-lg text-w-fg-1 border border-w-fg-1 leading-none",
          state.checked ? "bg-w-bg-active text-w-fg-1" : ""
        )}
        onClick={() => {
          store.toggle();
        }}
      >
        <div className="text-sm leading-tight">{label}</div>
      </div>
    );
  }
);

export const CheckboxGroup = <T extends any>(
  props: { store: CheckboxGroupCore<T> } & React.HTMLAttributes<HTMLDivElement>
) => {
  const { store } = props;

  const [state, setState] = useState(store.state);

  useInitialize(() => {
    store.onStateChange((nextState) => {
      setState(nextState);
    });
  });

  return (
    <div className="flex flex-wrap space-x-2">
      {state.options.map((option) => {
        const { label, value, core } = option;
        return <CheckboxOption key={label} store={core} label={label} />;
      })}
    </div>
  );
};
