// apps/web-solid/src/components/ui/image.tsx
// import { useEffect, useRef, useState } from "react";
import { Match, Switch, createSignal, onMount } from "solid-js";
import { JSX } from "solid-js/jsx-runtime";
import { effect } from "solid-js/web";
import { Image, ImageOff } from "lucide-solid";

import { ImageCore, ImageStep } from "@/domains/ui/image";
import { provide_ui_image } from "@timeless/provider-web";
import { cn } from "@/utils";

export function LazyImage(props: { store: ImageCore; alt?: string } & JSX.HTMLAttributes<HTMLImageElement>) {
  const { store } = props;

  let $img: HTMLImageElement | undefined = undefined;

  const [state, setState] = createSignal(store.state);

  store.onStateChange((v) => {
    // console.log("[COMPONENT]ui/image - store.onStateChange", v);
    setState(v);
  });
  onMount(() => {
    if (!$img) {
      return;
    }
    provide_ui_image(store, $img);
  });
  // effect(() => {
  //   if (!props.src) {
  //     return;
  //   }
  //   store.updateSrc(props.src);
  // });

  return (
    <div
      ref={$img}
      classList={{
        [props.class as string]: true,
        "flex items-center justify-center": true,
        "bg-slate-200": ![ImageStep.Loading, ImageStep.Loaded].includes(state().step),
      }}
    >
      <Switch>
        <Match when={state().step === ImageStep.Failed}>
          <ImageOff class="w-8 h-8 text-slate-500" />
        </Match>
        <Match when={state().step === ImageStep.Pending}>
          <Image class="w-8 h-8 text-slate-500" />
        </Match>
        <Match when={[ImageStep.Loading, ImageStep.Loaded].includes(state().step)}>
          <img
            class={props.class}
            style={{ "object-fit": state().fit }}
            src={state().src}
            alt={state().alt}
            onError={() => {
              store.handleError();
            }}
          />
        </Match>
      </Switch>
    </div>
  );
}

// apps/web-react/src/components/ui/image.tsx
import React, { useEffect, useRef, useState } from "react";
import { Image, ImageOff } from "lucide-react";

import { useInitialize } from "~/hooks";
import { ImageCore, ImageStep } from "@/domains/ui/image";
import { provide_ui_image } from "@timeless/provider-web";
import { cn } from "@/utils";

export const LazyImage = React.memo(
  (
    props: {
      store: ImageCore;
      alt?: string;
    } & React.HTMLAttributes<HTMLImageElement>
  ) => {
    const { store } = props;

    const $img = useRef<HTMLDivElement>(null);
    // const image = new ImageCore({ width: 200, height: 100, src: props.src, alt: props.alt });
    const [state, setState] = useState(store.state);

    useInitialize(() => {
      store.onStateChange((nextState) => {
        // console.log("[COMPONENT]LazyImage - image.onStateChange", nextState);
        setState(nextState);
      });
    });

    useEffect(() => {
      if (!$img.current) {
        return;
      }
      provide_ui_image(store, $img.current);
    }, []);
    // useEffect(() => {
    //   if (!props.src) {
    //     return;
    //   }
    //   store.updateSrc(props.src);
    // }, [props.src]);

    return (
      <div
        ref={$img}
        className={cn(
          props.className,
          "flex items-center justify-center bg-w-bg-0"
        )}
      >
        {(() => {
          if (state.step === ImageStep.Failed) {
            return <ImageOff className="w-8 h-8 text-w-fg-2" />;
          }
          if (state.step === ImageStep.Pending) {
            return <Image className="w-8 h-8 text-w-fg-2" />;
          }
          if ([ImageStep.Loading, ImageStep.Loaded].includes(state.step)) {
            return (
              <img
                className={props.className}
                // style={{
                //   objectFit: state.fit,
                // }}
                style={(() => {
                  const ss: React.CSSProperties = {
                    objectFit: state.fit,
                  };
                  if (state.scale) {
                    ss.transform = `scale(${state.scale})`;
                  }
                  return ss;
                })()}
                src={state.src}
                alt={state.alt}
                onError={() => {
                  store.handleError();
                }}
              />
            );
          }
          return null;
        })()}
      </div>
    );
  }
);
