// platform/solidjs/packages/ui/presence.tsx
/**
 * @file 控制内容显隐的组件
 */
import { JSX, createSignal } from "solid-js";

import { PresenceCore } from "@/domains/ui/presence";
import { cn } from "@/utils";

import { Show } from "./show";

export const Presence = (props: { store: PresenceCore } & JSX.HTMLAttributes<HTMLDivElement>) => {
  const [state, setState] = createSignal(props.store.state);

  props.store.onStateChange((v) => {
    setState(v);
  });

  return (
    <Show when={state().mounted}>
      <div
        class={cn("presence", props.class)}
        classList={props.classList}
        role="presentation"
        data-state={state().visible ? "open" : "closed"}
        onAnimationEnd={() => {
          props.store.unmount();
        }}
      >
        {props.children}
      </div>
    </Show>
  );
};

// apps/web-react/src/components/ui/presence.tsx
/**
 * @file 控制内容显隐的组件
 */
import React, { useState } from "react";

import { Show } from "~/packages/ui/show";
import { useInitialize } from "~/hooks/index";
import { PresenceCore } from "@/domains/ui/presence";
import { cn } from "@/utils/index";

export const Presence = React.memo(
  (
    props: {
      store: PresenceCore;
      enterClassName?: string;
      exitClassName?: string;
    } & React.AllHTMLAttributes<HTMLElement>
  ) => {
    const { store, enterClassName, exitClassName } = props;

    const [state, setState] = useState(store.state);

    useInitialize(() => {
      store.onStateChange((v) => setState(v));
    });

    const { visible, mounted, text } = state;

    return (
      <Show when={mounted}>
        <div
          className={cn(
            "presence",
            state.enter && enterClassName ? enterClassName : "",
            state.exit && exitClassName ? exitClassName : "",
            props.className
          )}
          role="presentation"
          style={{ display: visible ? "block" : "none" }}
          // data-state={visible ? "open" : "closed"}
          // onAnimationEnd={() => {
          //   store.unmount();
          // }}
        >
          {props.children}
        </div>
      </Show>
    );
  }
);
