// apps/web-react/src/components/ui/image.tsx
import React, { useEffect, useRef, useState } from "react";
import { Image, ImageOff } from "lucide-react";

import { useInitialize } from "~/hooks";
import { ImageCore, ImageStep } from "@/domains/ui/image";
import { provide_ui_image } from "@timeless/provider-web";
import { cn } from "@/utils";

export const LazyImage = React.memo(
  (
    props: {
      store: ImageCore;
      alt?: string;
    } & React.HTMLAttributes<HTMLImageElement>
  ) => {
    const { store } = props;

    const $img = useRef<HTMLDivElement>(null);
    // const image = new ImageCore({ width: 200, height: 100, src: props.src, alt: props.alt });
    const [state, setState] = useState(store.state);

    useInitialize(() => {
      store.onStateChange((nextState) => {
        // console.log("[COMPONENT]LazyImage - image.onStateChange", nextState);
        setState(nextState);
      });
    });

    useEffect(() => {
      if (!$img.current) {
        return;
      }
      provide_ui_image(store, $img.current);
    }, []);
    // useEffect(() => {
    //   if (!props.src) {
    //     return;
    //   }
    //   store.updateSrc(props.src);
    // }, [props.src]);

    return (
      <div
        ref={$img}
        className={cn(
          props.className,
          "flex items-center justify-center bg-w-bg-0"
        )}
      >
        {(() => {
          if (state.step === ImageStep.Failed) {
            return <ImageOff className="w-8 h-8 text-w-fg-2" />;
          }
          if (state.step === ImageStep.Pending) {
            return <Image className="w-8 h-8 text-w-fg-2" />;
          }
          if ([ImageStep.Loading, ImageStep.Loaded].includes(state.step)) {
            return (
              <img
                className={props.className}
                // style={{
                //   objectFit: state.fit,
                // }}
                style={(() => {
                  const ss: React.CSSProperties = {
                    objectFit: state.fit,
                  };
                  if (state.scale) {
                    ss.transform = `scale(${state.scale})`;
                  }
                  return ss;
                })()}
                src={state.src}
                alt={state.alt}
                onError={() => {
                  store.handleError();
                }}
              />
            );
          }
          return null;
        })()}
      </div>
    );
  }
);

// apps/web-vue/components/ui/Image.vue
<script setup lang="ts">
import { onMounted, watchEffect, ref } from "vue";
import { ImageOff, Image } from "lucide-vue-next";

import { ImageCore, ImageStep } from "@/domains/ui/image";
import { provide_ui_image } from "@timeless/provider-web";
import { cn } from "@/utils/index";

const props = defineProps<{ class?: string; store: ImageCore; src?: string; alt?: string }>();
const { store, src } = props;

function handleError() {
  store.handleError();
}

const state = ref(store.state);
const imgRef = ref();
store.onStateChange((nextState) => {
  state.value = nextState;
});
onMounted(() => {
  const $img = imgRef.value;
  if (!$img) {
    return;
  }
  provide_ui_image(store, $img);
});
const className = cn(props.class, "flex items-center justify-center text-w-fg-2 bg-w-bg-3");
</script>

<template>
  <div ref="imgRef" :class="className">
    <template v-if="state.step === ImageStep.Failed">
      <ImageOff :size="64" />
    </template>
    <template v-else-if="state.step === ImageStep.Pending">
      <Image :size="64" />
    </template>
    <template v-else-if="[ImageStep.Loading, ImageStep.Loaded].includes(state.step)">
      <img
        :style="{ width: '100%', height: '100%', 'object-fit': state.fit, transform: `scale(${state.scale})` }"
        :src="state.src"
        :alt="state.alt"
        @error="handleError"
      />
    </template>
  </div>
</template>
