// platform/solidjs/components/ui/input.tsx
import { JSX, createSignal, onMount } from "solid-js";
import { LoaderCircle } from "lucide-solid";

import { useViewModelStore } from "@/hooks";
import { Input as InputPrimitive } from "@/packages/ui/input";

import { InputCore } from "@/domains/ui/form/input";
import { connect } from "@/domains/ui/form/input/connect.web";
import { cn } from "@/utils";

const Input = (props: { store: InputCore<any>; prefix?: JSX.Element; class?: string }) => {
  // const { store, prefix } = props;

  const [state, vm] = useViewModelStore(props.store);
  // let ref: HTMLInputElement;
  // const [state, setState] = createSignal(store.state);

  // onMount(() => {
  //   const $input = ref;
  //   if (!$input) {
  //     return;
  //   }
  //   connect(store, $input);
  //   store.setMounted();
  // });
  // store.onStateChange((nextState) => {
  //   setState(nextState);
  // });

  // React.useEffect(() => {
  //   return () => {
  //     console.log("Input unmounted");
  //   };
  // }, []);
  // console.log("[]Input");
  return (
    <div
      class="relative w-full"
      onClick={(event) => {
        const { x, y } = event;
        vm.handleClick({ x, y });
      }}
    >
      <div class="absolute left-3 top-[50%] translate-y-[-50%] text-slate-400 ">
        {(() => {
          if (!props.prefix) {
            return null;
          }
          if (state().loading) {
            return <LoaderCircle class="w-4 h-4 animate-spin" />;
          }
          return props.prefix;
        })()}
      </div>
      <InputPrimitive
        class={cn(
          "flex items-center h-10 w-full rounded-xl leading-none border-2 border-w-fg-3 py-2 px-3 text-w-fg-0 bg-transparent",
          "focus:outline-none focus:ring-w-bg-3",
          "disabled:cursor-not-allowed disabled:opacity-50",
          "placeholder:text-w-fg-2",
          props.prefix ? "pl-8" : "",
          props.class
        )}
        style={{
          "vertical-align": "bottom",
        }}
        store={vm}
      />
    </div>
  );
};
Input.displayName = "Input";

export { Input };

// apps/web-vue/components/ui/Input.vue
<script setup lang="ts">
import { onMounted, ref } from "vue";

import { InputCore } from "@/domains/ui/form/input";
import { provide_ui_input } from "@timeless/provider-web";
import { cn } from "@/utils/index";

const props = defineProps<{
  store: InputCore<any>;
  class?: string;
}>();
const { store } = props;

const state = ref(store.state);
const r = ref();

function handleChange(event: Event) {
  store.handleChange(event);
}
onMounted(() => {
  const $input = r.value;
  if (!$input) {
    return;
  }
  provide_ui_input(store, $input);
});
store.onStateChange((nextState) => {
  state.value = nextState;
});

const className = cn(
  "flex h-10 w-full rounded-md border border-slate-300 bg-transparent py-2 px-3 text-sm placeholder:text-slate-400 focus:outline-none focus:ring-2 focus:ring-slate-400 focus:ring-offset-2 disabled:cursor-not-allowed disabled:opacity-50 dark:border-slate-700 dark:text-slate-50 dark:focus:ring-slate-400 dark:focus:ring-offset-slate-900",
  props.class
);
</script>

<template>
  <input
    ref="r"
    :class="className"
    :value="state.value"
    :placeholder="state.placeholder"
    :disabled="state.disabled"
    :type="state.type"
    @change="handleChange"
  />
</template>
