// platform/react/pages/login/index.tsx
import React, { useEffect } from "react";

import { ViewComponent, ViewComponentProps } from "~/store/types";
import { useInstance } from "~/hooks/index";
import { Button, Input } from "~/components/ui";
import { ButtonCore, InputCore } from "@/domains/ui";
import { MediaOriginCountry } from "~/biz/constants/index";

function Page(props: ViewComponentProps) {
  const { app, view, history } = props;
  const $view = view;
  const $username = new InputCore({
    defaultValue: "",
    placeholder: "请输入邮箱",
  });
  const $password = new InputCore({
    defaultValue: "",
    placeholder: "请输入密码",
    type: "password",
    autoComplete: true,
    onEnter() {
      $login.click();
    },
  });
  const $login = new ButtonCore({
    async onClick() {
      const values = {
        email: $username.value,
        pwd: $password.value,
      };
      $login.setLoading(true);
      const r = await app.$user.loginWithEmailAndPwd(values);
      $login.setLoading(false);
      if (r.error) {
        app.tip({
          text: [r.error.message],
        });
        return;
      }
      app.tip({
        text: ["登录成功"],
      });
      // const { redirect } = view.query as { redirect: PageKeys };
      // if (redirect) {
      //   history.replace(redirect, {});
      //   return;
      // }
      history.replace("root.home_layout.home_index.home_index_season", {
        language: MediaOriginCountry.CN,
      });
      // const route = routesWithPathname[pathname];
      // console.log("[PAGE]login/index", pathname, route, app.$user.isLogin);
    },
  });
  const $register = new ButtonCore({
    onClick() {
      history.push("root.register");
    },
  });
  const $home = new ButtonCore({
    onClick() {
      history.push("root.home_layout.home_index", {
        language: MediaOriginCountry.CN,
      });
    },
  });

  return {
    ui: {
      $username,
      $password,
      $login,
      $register,
      $home,
    },
  };
}

export const LoginPage: ViewComponent = React.memo((props) => {
  const { app, client, view, history } = props;

  const $page = useInstance(() => Page(props));

  return (
    <div className="pt-12 px-4 min-h-screen bg-w-bg-0">
      <div className="h-[160px] mx-auto">
        <div className="relative cursor-pointer">
          <div className="z-10 absolute left-14 top-[32px] w-[82%] h-[32px] rounded-xl bg-green-500"></div>
          <div className="z-20 relative text-6xl text-center italic">
            FamilyFlix
          </div>
        </div>
      </div>
      <div className="space-y-4 rounded-md">
        <div>
          <div>邮箱</div>
          <Input className="mt-1 bg-w-bg-0" store={$page.ui.$username} />
        </div>
        <div>
          <div>密码</div>
          <Input className="mt-1 bg-w-bg-0" store={$page.ui.$password} />
        </div>
      </div>
      <div className="w-full mt-8">
        <Button size="lg" store={$page.ui.$login}>
          登录
        </Button>
        <div
          className="mt-1 py-2 text-center text-w-fg-1 cursor-pointer hover:underline"
          onClick={() => {
            history.push("root.register");
          }}
        >
          没有账号，前往注册
        </div>
        {app.$user.isLogin ? (
          <div className="mt-2">
            <Button size="lg" variant="subtle" store={$page.ui.$home}>
              前往首页
            </Button>
            <div className="mt-1 text-sm text-w-fg-2 text-center">
              检测到当前已登录
            </div>
          </div>
        ) : null}
      </div>
    </div>
  );
});

// apps/web-vue/pages/login/index.vue
<script setup lang="ts">
import { onMounted, ref } from "vue";

import { ViewComponentProps } from "../../store/types";
import Input from "@/components/ui/Input.vue";
import Button from "@/components/ui/Button.vue";
import { QRCodeWithState } from "@/biz/qrcode_confirm/index";
import { createQRCode } from "@/domains/qrcode/index";
import { ButtonCore, InputCore } from "@/domains/ui/index";
import { AuthCodeStep } from "@/constants/index";

const props = defineProps<ViewComponentProps>();
const { history } = props;

function Page(props: ViewComponentProps) {
  const { app, view, history, client } = props;

  const $username = new InputCore({
    defaultValue: "",
    placeholder: "请输入邮箱",
  });
  const $password = new InputCore({
    defaultValue: "",
    placeholder: "请输入密码",
    type: "password",
    autoComplete: true,
  });
  const $login = new ButtonCore({
    async onClick() {
      const values = {
        email: $username.value,
        pwd: $password.value,
      };
      $login.setLoading(true);
      const r = await app.$user.loginWithEmailAndPwd(values);
      $login.setLoading(false);
      if ((r as any).error) {
        app.tip({
          text: ["登录失败", (r as any).error.message],
        });
        return;
      }
      app.tip({
        text: ["登录成功"],
      });
      history.replace("root.home_layout.home_index", {});
    },
  });
  const $code = QRCodeWithState({ unique_id: view.query.code, step: AuthCodeStep.Loading, client });
  $code.onConfirm(async (v) => {
    const r2 = await app.$user.authWithToken(v);
    const r2_any = r2 as any;
    if (r2_any.error) {
      app.tip({
        text: ["登录失败", r2_any.error.message],
      });
      return;
    }
    app.tip({
      text: ["登录成功"],
    });
    history.replace("root.home_layout.home_index", {});
  });

  return {
    $code,
    ui: {
      $username,
      $password,
      $login,
    },
  };
}

const $page = Page(props);
const qrcodeRef = ref<HTMLCanvasElement>();
const qrcode = ref($page.$code.state);
function refreshQRCode() {
  $page.$code.refresh();
}

$page.$code.onStateChange((v) => {
  console.log("$page.$code.onStateChange", v, $page.$code.state);
  qrcode.value = v;
});

onMounted(async () => {
  const $canvas = qrcodeRef.value;
  if (!$canvas) {
    return;
  }
  const ctx = $canvas.getContext("2d");
  if (!ctx) {
    return;
  }
  const r = await $page.$code.refresh();
  if ((r as any).error) {
    props.app.tip({
      text: [(r as any).error.message],
    });
    return;
  }
  $page.$code.startCheck();
  const hostname = (() => {
    if (props.app.env.prod === "develop") {
      return "https://media-t.funzm.com";
    }
    return history.$router.origin;
  })();
  createQRCode(`${hostname}/mobile/scan?code=${r.data.id}`, { width: 198, height: 198, ctx });
});
</script>

<template>
  <div class="w-full h-screen">
    <div class="w-[920px] mx-auto pt-12">
      <div class="relative w-[136px] cursor-pointer">
        <div class="z-10 absolute left-2 top-[36px] w-[280px] h-[32px] rounded-2xl bg-green-500"></div>
        <div class="z-20 relative text-w-bg-1 text-6xl italic">FamilyFlix</div>
      </div>
      <div class="flex mt-8 min-h-[480px] border rounded-xl shadow-xl">
        <div class="flex items-center justify-center w-[360px]">
          <div class="qrcode relative inline-block p-2 border">
            <canvas ref="qrcodeRef" class="z-10 relative" width="198" height="198"></canvas>
            <template v-if="qrcode.step === AuthCodeStep.Loading">
              <div class="z-20 absolute inset-0">
                <div class="z-10 absolute inset-0 bg-white opacity-80"></div>
                <div class="z-20 absolute inset-0 flex items-center justify-center">
                  <div class="flex flex-col items-center justify-center">加载中</div>
                </div>
              </div>
            </template>
            <template v-if="qrcode.step === AuthCodeStep.Scanned">
              <div class="z-20 absolute inset-0">
                <div class="z-10 absolute inset-0 bg-white opacity-80"></div>
                <div class="z-20 absolute inset-0 flex items-center justify-center">
                  <div class="flex flex-col items-center justify-center">
                    <div class="text-lg">请确认登录</div>
                  </div>
                </div>
              </div>
            </template>
            <template v-if="qrcode.step === AuthCodeStep.Confirmed">
              <div class="z-20 absolute inset-0">
                <div class="z-10 absolute inset-0 bg-white opacity-80"></div>
                <div class="z-20 absolute inset-0 flex items-center justify-center">
                  <div class="flex flex-col items-center justify-center">
                    <div class="text-lg">已确认</div>
                  </div>
                </div>
              </div>
            </template>
            <template v-if="qrcode.step === AuthCodeStep.Expired">
              <div class="z-20 absolute inset-0" @click="refreshQRCode">
                <div class="z-10 absolute inset-0 bg-white opacity-80"></div>
                <div class="z-20 absolute inset-0 flex items-center justify-center">
                  <div class="flex flex-col items-center justify-center">
                    <div class="text-lg">二维码失效</div>
                  </div>
                </div>
              </div>
            </template>
            <template v-if="qrcode.step === AuthCodeStep.Error">
              <div class="z-20 absolute inset-0" @click="refreshQRCode">
                <div class="z-10 absolute inset-0 bg-white opacity-80"></div>
                <div class="z-20 absolute inset-0 flex items-center justify-center">
                  <div class="flex flex-col items-center justify-center">
                    <div class="text-lg">发生错误</div>
                    <div class="mt-1 text-center">{{ qrcode.error?.message }}</div>
                  </div>
                </div>
              </div>
            </template>
          </div>
          <!-- <div>使用微信扫码登录</div> -->
        </div>
        <div class="flex-1 flex items-center justify-center">
          <div class="w-[320px]">
            <div className="space-y-4 rounded-md">
              <div>
                <div class="text-w-bg-1">邮箱</div>
                <Input class="mt-1 bg-w-bg-0" :store="$page.ui.$username" />
              </div>
              <div>
                <div class="text-w-bg-1">密码</div>
                <Input class="mt-1 bg-w-bg-0" :store="$page.ui.$password" />
              </div>
            </div>
            <div className="w-full mt-8">
              <Button variant="" size="lg" class="w-full" :store="$page.ui.$login">登录</Button>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

<style scoped></style>
@/biz/qrcode_confirm/index
