// apps/web-solid/src/components/ui/toast.tsx
/**
 * @file 小黑块 提示
 */
import { For, createSignal, JSX, Show } from "solid-js";
import { Loader } from "lucide-solid";

import * as ToastPrimitive from "~/packages/ui/toast";
import { ToastCore } from "@/domains/ui/toast";
import { cn } from "@/utils";

export const Toast = (props: { store: ToastCore }) => {
  const [state, setState] = createSignal(props.store.state);
  props.store.onStateChange((v) => {
    setState(v);
  });

  return (
    <ToastPrimitive.Root store={props.store}>
      <ToastPrimitive.Portal store={props.store}>
        {/* <Show when={state().mask || state().icon === "loading"}>
          <ToastPrimitive.Overlay
            store={props.store}
            classList={{
              "fixed inset-0 z-100 bg-black/50 transition-all duration-200": true,
              "animate-in fade-in": state().enter,
              "animate-out fade-out": state().exit,
            }}
          />
        </Show> */}
        <div
          classList={{
            "fixed z-[99999] left-1/2 -translate-x-1/2 top-1/2 -translate-y-1/2": true,
          }}
        >
          <ToastPrimitive.Content
            store={props.store}
            classList={{
              // "p-6 w-120 h-120 ": true,
              "relative duration-200": true,
              "animate-in fade-in": state().enter,
              "animate-out fade-out": state().exit,
            }}
          >
            <div class="z-0 absolute inset-0 rounded-xl bg-black opacity-90"></div>
            <div class="z-10 relative space-y-4 p-6 w-80">
              <Show when={state().icon === "loading"}>
                <div class="relative left-1/2 w-6 h-6 -translate-x-1/2">
                  <Loader class="w-full h-full animate-spin" />
                </div>
              </Show>
              <Show when={state().texts.length}>
                <div class="">
                  <For each={state().texts}>
                    {(text) => {
                      return <div class="text-center text-white">{text}</div>;
                    }}
                  </For>
                </div>
              </Show>
            </div>
          </ToastPrimitive.Content>
        </div>
      </ToastPrimitive.Portal>
    </ToastPrimitive.Root>
  );
};

// platform/react/components/ui/toast.tsx
/**
 * @file 小黑块 提示
 */
import React, { useState } from "react";

import { useInitialize } from "~/hooks/index";
import * as ToastPrimitive from "~/packages/ui/toast";
import { ToastCore } from "@/domains/ui/toast";
import { cn } from "@/utils/index";

export const Toast = React.memo((props: { store: ToastCore }) => {
  const { store } = props;

  const [state, setState] = useState(store.state);
  const [state2, setState2] = useState(store.$present.state);

  useInitialize(() => {
    store.onStateChange((nextState) => {
      setState(nextState);
    });
    store.$present.onStateChange((v) => setState2(v));
  });

  const { texts } = state;

  return (
    <ToastPrimitive.Root store={store}>
      <ToastPrimitive.Portal
        store={store}
        className={cn(
          state2.enter ? "animate-in fade-in" : "",
          state2.exit ? "animate-out fade-out" : ""
        )}
      >
        <ToastPrimitive.Content
          store={store}
          className={cn(
            "grid gap-4 rounded-lg bg-w-bg-4 text-w-bg-0 dark:text-w-fg-0 p-6 duration-200 sm:max-w-lg sm:rounded-lg",
            state2.enter ? "animate-in fade-in sm:zoom-in-90" : "",
            state2.exit ? "animate-out fade-out" : ""
          )}
        >
          {texts.map((text, i) => {
            return (
              <div key={i} className="text-center">
                {text}
              </div>
            );
          })}
        </ToastPrimitive.Content>
      </ToastPrimitive.Portal>
    </ToastPrimitive.Root>
  );
});

// const Overlay = (props: { store: ToastCore } & React.AllHTMLAttributes<HTMLDivElement>) => {
//   const { store } = props;

//   const [state, setState] = useState(store.$present.state);

//   useInitialize(() => {
//     store.$present.onStateChange((v) => setState(v));
//   });

//   return (
//     <ToastPrimitive.Overlay
//       store={store}
//       className={cn(
//         "fixed inset-0 z-51 bg-black/50 backdrop-blur-sm transition-all duration-100",
//         // "data-[state=exit]:animate-out data-[state=enter]:fade-in data-[state=exit]:fade-out",
//         state.enter ? "animate-in fade-in" : "",
//         state.exit ? "animate-out fade-out" : "",
//         props.className
//       )}
//     />
//   );
// };
